org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.95

mod_id=primevalworks
mod_name=Primeval Works
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.primevalworks
geckolib_version=5.5.2
jei_version=29.29.0.77
